In [1]:
str = "HEllo"
print(str, type(str))

tup = (1,2,3,4)
print(tup, type(tup))

num = 12
print(num, type(num))

li = [1,2,3,4,5]
print(li, type(li))

set1 = {1,2,3,4,5}
frozen = frozenset(set1)
print(set1,type(set1))
print(frozen, type(frozen)) 

bool = True
print(bool, type(bool))

HEllo <class 'str'>
(1, 2, 3, 4) <class 'tuple'>
12 <class 'int'>
[1, 2, 3, 4, 5] <class 'list'>
{1, 2, 3, 4, 5} <class 'set'>
frozenset({1, 2, 3, 4, 5}) <class 'frozenset'>
True <class 'bool'>


In [17]:
str = "Hello world"
print(str[1:4]) #string slicing
print(str[::-1]) #reversing string
print(str[6]) #printing individual characters

str = str+ " deez nuts"
print(str)#printing concatinated string
print(str*3)
print("Hello %s" %str)

#membership operator
arr = ["Hello", "world"]

print(str[:5] in arr)

#identity operator
print(str is arr)

str2 = str
print(str is str2)




ell
dlrow olleH
w
Hello world deez nuts
Hello world deez nutsHello world deez nutsHello world deez nuts
Hello Hello world deez nuts
True
False
True


In [18]:
str = "Hello my name is deez nuts"

dict = {
    "str": len(str)
}
print(dict)

{'str': 26}


Assignment 3


In [3]:
#creation of a list
l1 = [1,2,3,4,5]

#accessing the list
print("Accessing elements in a l1:")
print(l1[2])

#joining the list
print("Joining lists")
l2 = ["Hello","I","am","deez"]
l2 = l1+l2
print(l2)

#replacing elements in a list
print("Replacing elements in a list")
l2 = ["Hello", "I", "am", "deez"]
l2[3] = "Vaibhav"
print(l2)

#replicating a list
l3 = l1
print("Replicated list:", l3)

#list slicing
print("List slicing")
print(l2[1:])
print(l2[:])
print(l2[:3])
print(l2[::-1])

Accessing elements in a l1:
3
Joining lists
[1, 2, 3, 4, 5, 'Hello', 'I', 'am', 'deez']
Replacing elements in a list
['Hello', 'I', 'am', 'Vaibhav']
Replicated list: [1, 2, 3, 4, 5]
List slicing
['I', 'am', 'Vaibhav']
['Hello', 'I', 'am', 'Vaibhav']
['Hello', 'I', 'am']
['Vaibhav', 'am', 'I', 'Hello']


Program to sum up all the items in a list
Program to get largest number from a list
Program to check list is empty or not
Program to clone or copy a list
Program that takes 2 lists and returns true if they have, atleast one common member
Program to generate and print a list of first 5 and last 5 elements where the values are the square of numbers between 1 and 30 (both included)
Program to print a specified list after removing the even numbers from it
Program to print a specified list after removing 0th, 4th and 5th elements from that list

In [11]:
#Program to sum up all the items in a list
l1 = [1,2,3,4,5]
print(sum(l1))
#Program to get largest number from a list
print(max(l1))
#Program to check list is empty or not
if(len(l1) == 0):
    print("Empty list")
else:
    print("list is not empty")

#Program to clone or copy a list
l2 = l1
print(l2)

#Program that takes 2 lists and returns true if they have, atleast one common member
def common_member(l1,l2):
    if l1 in l2:
        return True
    return False

print(common_member(l1,l2))
#Program to generate and print a list of first 5 and last 5 elements where the values are the square of numbers between 1 and 30 (both included)
list_pow = []
for i in range(1,31):
    list_pow.append(pow(i,2))
print("First 5 elements", list_pow[:5])
print("Last 5 elements:",list_pow[-5:])

list_remove_even = []
for i in range(1,10):
    list_remove_even.append(i)

#Program to print a specified list after removing the even numbers from it
poplist = []
for i in range(0,len(list_remove_even)-1):
    if list_remove_even[i] %2 == 0:
        poplist.append(list_remove_even[i])
for ele in poplist:
    list_remove_even.remove(ele)


#Program to print a specified list after removing 0th, 4th and 5th elements from that list

remove_list = [1,2,3,4,5,6,7,8]
remove_list.pop(0)
remove_list.pop(4)
remove_list.pop(5)
print(remove_list)


15
5
list is not empty
[1, 2, 3, 4, 5]
False
First 5 elements [1, 4, 9, 16, 25]
Last 5 elements: [676, 729, 784, 841, 900]
[2, 3, 4, 5, 7]


In [3]:
#Assignment 4
#creating tuple
tup = (1,2,3,4,5)
#accessing tuple
print(tup[1])
#joining tuples
tup1 = (4,5,6)
print(tup+tup1)
#replicating tuples
tup2 = tup1
print(tup2)
#slicing tuples
print(tup[2:-1])


2
(1, 2, 3, 4, 5, 4, 5, 6)
(4, 5, 6)
(3, 4)


Assignment 5
Write a program to demonstrate use of Dictionaries in python and perform: Accessing values in
dictionaries, Working with dictionaries- Create, Merge, Delete set of keys, Rename.


In [15]:
#creating
dict = {
    "name": "vaibhav",
    "class": "syit"
}
#accessing
print(dict["name"])

#merging
dict2 = {
    "subject": "itw2"
}
dict2.update(dict)
print(dict2)

#deleting keys
del dict2["subject"]
print(dict2)

#renaming
dict2["subject"] = "dsa"
print(dict2)


vaibhav
{'subject': 'itw2', 'name': 'vaibhav', 'class': 'syit'}
{'name': 'vaibhav', 'class': 'syit'}
{'name': 'vaibhav', 'class': 'syit', 'subject': 'dsa'}


Assignment 6
Write a program to demonstrate use of Set and Frozenset in python and perform: Creating Set and
Frozenset, Accessing and Joining, Replicating and Slicing

In [24]:
#creating a set and frozenset

set1 = {1,2,3,4,5,6}
set2 = {'a', 'b', 'c'}
setFrozen = frozenset(set1)

print(set1)
print(setFrozen)

#joining values in a set
set1.update(set2)
print(set1)

#accessing values in set
for val in set1:
    print(val)

#replicating values 
setCopy = set1
print(setCopy)

#slicing in set
list1 = list(set1)
x = slice(1,4)
print(list1[x])

#set operations
sa = {1,2,3,4,5}
sb = {5,6,7,8,9,10}
print(sa.difference(sb))
print(sa.union(sb))
print(sa.intersection(sb))
print(sa.symmetric_difference(sb))
print(sa<sb)
sa = sb
print(sa == sb)


{1, 2, 3, 4, 5, 6}
frozenset({1, 2, 3, 4, 5, 6})
{1, 2, 3, 4, 5, 6, 'c', 'a', 'b'}
1
2
3
4
5
6
c
a
b
{1, 2, 3, 4, 5, 6, 'c', 'a', 'b'}
[2, 3, 4]
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{5}
{1, 2, 3, 4, 6, 7, 8, 9, 10}
False
True


Assignment 7
Functions in Python: function creation, function calls, function arguments, inner functions, built-in
functions.
Create a function showEmployee() in such a way that it should accept the employee name, and its
salary and display both. If the salary is missing in the function call assign default value 9000 to salary.

In [3]:
#function creation and calling
#inner function
def helloPrinter(name):
    print("Hello",name)
    def yourMom():
        print("ya mom")
    yourMom()
helloPrinter("Vaibhav")

#built in functions
list = []
list.append("hello")

def showEmployee(name, salary = 9000):
    print("Employe name:", name)
    print("Salary:",salary)

showEmployee("Emp1")
showEmployee("Emp2",20000)

def add(x,y):
    return x+y


Hello Vaibhav
ya mom
Employe name: Emp1
Salary: 9000
Employe name: Emp2
Salary: 20000
3


In [10]:
def varlength(*num):
    print(num)
    for val in num:
        if val > 0:
            print(val)
varlength(1,2,3,-2)

(1, 2, 3, -2)
1
2
3


In [10]:
import numpy as np
a1 = np.array([[6,6,7],[9,8,3]])
a2 = np.array([[5,6,2],[7,8,1]])
result = a1+a2
print("addition of 2 arrays: ", result)
for num in np.nditer(result,op_flags=['readwrite']):
    num[...] = num*num
print("After squaring: ", result)
print("After sorting: ", np.sort(result))
print("After splitting: ", np.array_split(result, 3))

addition of 2 arrays is:  [[11 12  9]
 [16 16  4]]
After squaring:  [[121 144  81]
 [256 256  16]]
After sorting:  [[ 81 121 144]
 [ 16 256 256]]
After splitting:  [array([[121, 144,  81]]), array([[256, 256,  16]]), array([], shape=(0, 3), dtype=int32)]
